file = open('C:\\labmanualprograms\\file1.txt', 'w')
file.write("hello world")
file.close()
file = open('C:\\labmanualprograms\\file1.txt', 'r')
content = file.read()
print("file1:",content) 
file.close()
file_copy = open('C:\\labmanualprograms\\file2.txt', 'w')
file_copy.write(content)
file_copy.close()
